export const enum USER_ERR {
  ACCOUNT_EXIST = 'ACCOUNT_EXIST',
  EMAIL_EXIST = 'EMAIL_EXIST',
  EMAIL_NOT_EXIST = 'EMAIL_NOT_EXIST',
  CODE_ERROR = 'CODE_ERROR',
  NOT_CORRECT = 'NOT_CORRECT',
}

export const enum USER_SEX {
  UNKNOWN,
  MALE,
  FEMALE,
}

export const enum SUBMISSION_STATUS {
  TO_BE_REVIEWED,
  PASS,
  NOT_PASS,
  RE_REVIEW,
  BANNED,
}

export const enum SUBMISSION_TYPE {
  ARTICLE,
  VIDEO,
}
